### ISSUE TITLE
`treegraph` chart type not working

### ISSUE THREAD

**Issue by emistler** [zauberzeug/nicegui-highcharts#12]
I've got a `treegraph` chart (simplified), which I tested in JSFiddle and then adapted for python:

```python
def my_chart():
    data = [
        {"id": "step-1", "name": "Step 1", "color": "red"},
        {"id": "step-2", "name": "Step 2", "parent": "ingestion", "color": "grey"},
    ]

    return ui.highchart(
        {
            "title": {"text": ""},
            "series": [
                {
                    "type": "treegraph",
                    "data": data,
                    "tooltip": {"pointFormat": "{point.name}"},
                    "marker": {"symbol": "rect", "width": "25%"},
                    "borderRadius": 5,
                    "dataLabels": {
                        "pointFormat": "{point.name}",
                        "style": {"whiteSpace": "nowrap"},
                    },
                }
            ],
        }
    )
```

When I load a NiceGUI application with this chart embedded, I am getting the follow error (in the browser console, NiceGUI itself seems happy enough):

```
vue.global.prod.js:5 Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=treegraph
 - missingModuleFor: treegraph
    at Object.<anonymous> (highcharts.js:8:138)
    at M (highcharts.js:8:2591)
    at o (highcharts.js:8:61)
    at Q.initSeries (highcharts.js:8:197051)
    at highcharts.js:8:212230
    at Proxy.forEach (<anonymous>)
    at Q.firstRender (highcharts.js:8:212208)
    at Q.<anonymous> (highcharts.js:8:196969)
    at M (highcharts.js:8:2591)
    at Q.init (highcharts.js:8:196387)
```

I take this to mean that the vue library for `treegraph` is not loaded. However, I can find the path `.venv/lib/python3.11/site-packages/nicegui_highcharts/lib/highcharts/modules/treegraph.js` and since the `Highchart` class itself is initialised with the following, I was expecting this to work:

```python
  dependencies=[
                    'lib/highcharts/*.js',
                    'lib/highcharts/modules/*.js',
                ]
```

And indeed, I can find the following entry in `ui.highchart.exposed_libraries`:

```
Library(key='36fb47e853cb0c7e42f708da1527b47e/treegraph.js', name='treegraph', path=PosixPath('/Users/elias/dev/hackathon-lumberjacks/.venv/lib/python3.11/site-packages/nicegui_highcharts/lib/highcharts/modules/treegraph.js'), expose=True)
```

So I'm a bit lost as to why I am getting the issue.

Just to confirm, if I change the graph type to e.g. `line`, it does render. Obviously, the series isn't compatible, but I then at least see the axes rendered.

**Comment by iamdavidmt** [comment]
do you need to specify it somehow...

**Comment by iamdavidmt** [comment]
there is this; https://nicegui.io/documentation/highchart#chart_with_extra_dependencies maybe like

`extras=["treegraph"]`

**Comment by alastairhamilton** [comment]
```
import plotly.graph_objects as go
from nicegui import ui

# Define the nodes and their positions
nodes = {
    "A": (0, 0),
    "B": (1, 1),
    "C": (2, 0),
    "D": (3, 1),
    "E": (4, 0),
}

# Define the edges (connections between nodes)
edges = [
    ("A", "B"),
    ("B", "C"),
    ("B", "D"),
    ("C", "E"),
    ("D", "E"),
]

# Extract x, y positions for nodes
node_x = [pos[0] for pos in nodes.values()]
node_y = [pos[1] for pos in nodes.values()]
node_labels = list(nodes.keys())

# Create edge traces
edge_shapes = []
for edge in edges:
    x0, y0 = nodes[edge[0]]
    x1, y1 = nodes[edge[1]]
    edge_shapes.append(
        dict(
            type="line",
            x0=x0,
            y0=y0,
            x1=x1,
            y1=y1,
            line=dict(width=2, color="gray"),
        )
    )

# Create the scatter plot for nodes
node_trace = go.Scatter(
    x=node_x,
    y=node_y,
    mode="markers+text",
    marker=dict(size=15, color="blue"),
    text=node_labels,
    textposition="top center",
    hoverinfo="text",
)

# Create the figure
fig = go.Figure()
fig.add_trace(node_trace)
fig.update_layout(
    shapes=edge_shapes,
    xaxis=dict(showgrid=False, zeroline=False),
    yaxis=dict(showgrid=False, zeroline=False),
    margin=dict(l=0, r=0, t=0, b=0),
)

# Define a callback to handle clicks
def on_click(event):
    plotly_data = event.args
    clicked_node = plotly_data["points"][0]
    clicked_node_label = clicked_node["text"]
    ui.notify(f"You clicked on node: {clicked_node_label}")

# Embed the Plotly figure into the NiceGUI app and bind the click event
ui.plotly(fig).on("plotly_click", on_click).classes('w-full h-80')

# Run the NiceGUI application
ui.run()
```

This gives:
![image](https://github.com/user-attachments/assets/9f6a1474-678d-414a-90bf-55889a2f803b)
And supports onclick events

**Comment by falkoschindler** [comment]
Adding `extras=['treegraph']` is the correct way to add the tree graph dependency.
But I don't know why Highcharts is complaining about reading a `prototype` property. 😕
